### ISSUE TITLE
LGT8F328P

### ISSUE THREAD

**Issue by miathedev** [Edragon/LGT#1]
Dear Edragon,

do you know how to flash an Arduino sketch to the LGT8F328P (without bootloader) using Arduino as ISP?
I only found documents how to flash the LGT8F328D.

**Comment by Upcycle-Electronics** [comment]
@miathedev  Where did you find these docs for the 328D?

**Comment by hechao** [comment]
Hello, flash by arduino is out of date, problematic, it is better to use the official programmer, simple and easy. 
We already give up the arduino method, sorry.

**Comment by miathedev** [comment]
Thats bad...

From where did you buy the programmer?
Do you got any "trusted" source?

**Comment by hechao** [comment]
You can buy from us from electrodragon, the regular LGT 328P is preloaded with arduino chip, not really need programmer. Please email to info@electrodragon.com

LGT also have many other good chips, If you need the programmer please also email. I don't know other source, it is pretty rare thing.
